// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockISendEmail is an autogenerated mock type for the ISendEmail type
type MockISendEmail struct {
	mock.Mock
}

type MockISendEmail_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISendEmail) EXPECT() *MockISendEmail_Expecter {
	return &MockISendEmail_Expecter{mock: &_m.Mock}
}

// SendEmail provides a mock function with given fields: ctx, payload
func (_m *MockISendEmail) SendEmail(ctx context.Context, payload interface{}) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISendEmail_SendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmail'
type MockISendEmail_SendEmail_Call struct {
	*mock.Call
}

// SendEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - payload interface{}
func (_e *MockISendEmail_Expecter) SendEmail(ctx interface{}, payload interface{}) *MockISendEmail_SendEmail_Call {
	return &MockISendEmail_SendEmail_Call{Call: _e.mock.On("SendEmail", ctx, payload)}
}

func (_c *MockISendEmail_SendEmail_Call) Run(run func(ctx context.Context, payload interface{})) *MockISendEmail_SendEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MockISendEmail_SendEmail_Call) Return(_a0 error) *MockISendEmail_SendEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISendEmail_SendEmail_Call) RunAndReturn(run func(context.Context, interface{}) error) *MockISendEmail_SendEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockISendEmail creates a new instance of MockISendEmail. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISendEmail(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISendEmail {
	mock := &MockISendEmail{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
