// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIWorkerService is an autogenerated mock type for the IWorkerService type
type MockIWorkerService struct {
	mock.Mock
}

type MockIWorkerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIWorkerService) EXPECT() *MockIWorkerService_Expecter {
	return &MockIWorkerService_Expecter{mock: &_m.Mock}
}

// ConsumeJobs provides a mock function with given fields: ctx
func (_m *MockIWorkerService) ConsumeJobs(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeJobs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIWorkerService_ConsumeJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeJobs'
type MockIWorkerService_ConsumeJobs_Call struct {
	*mock.Call
}

// ConsumeJobs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIWorkerService_Expecter) ConsumeJobs(ctx interface{}) *MockIWorkerService_ConsumeJobs_Call {
	return &MockIWorkerService_ConsumeJobs_Call{Call: _e.mock.On("ConsumeJobs", ctx)}
}

func (_c *MockIWorkerService_ConsumeJobs_Call) Run(run func(ctx context.Context)) *MockIWorkerService_ConsumeJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIWorkerService_ConsumeJobs_Call) Return(_a0 error) *MockIWorkerService_ConsumeJobs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIWorkerService_ConsumeJobs_Call) RunAndReturn(run func(context.Context) error) *MockIWorkerService_ConsumeJobs_Call {
	_c.Call.Return(run)
	return _c
}

// StartWorker provides a mock function with given fields: _a0
func (_m *MockIWorkerService) StartWorker(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for StartWorker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIWorkerService_StartWorker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartWorker'
type MockIWorkerService_StartWorker_Call struct {
	*mock.Call
}

// StartWorker is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockIWorkerService_Expecter) StartWorker(_a0 interface{}) *MockIWorkerService_StartWorker_Call {
	return &MockIWorkerService_StartWorker_Call{Call: _e.mock.On("StartWorker", _a0)}
}

func (_c *MockIWorkerService_StartWorker_Call) Run(run func(_a0 context.Context)) *MockIWorkerService_StartWorker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIWorkerService_StartWorker_Call) Return(_a0 error) *MockIWorkerService_StartWorker_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIWorkerService_StartWorker_Call) RunAndReturn(run func(context.Context) error) *MockIWorkerService_StartWorker_Call {
	_c.Call.Return(run)
	return _c
}

// StopWorker provides a mock function with given fields: _a0
func (_m *MockIWorkerService) StopWorker(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for StopWorker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIWorkerService_StopWorker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopWorker'
type MockIWorkerService_StopWorker_Call struct {
	*mock.Call
}

// StopWorker is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockIWorkerService_Expecter) StopWorker(_a0 interface{}) *MockIWorkerService_StopWorker_Call {
	return &MockIWorkerService_StopWorker_Call{Call: _e.mock.On("StopWorker", _a0)}
}

func (_c *MockIWorkerService_StopWorker_Call) Run(run func(_a0 context.Context)) *MockIWorkerService_StopWorker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIWorkerService_StopWorker_Call) Return(_a0 error) *MockIWorkerService_StopWorker_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIWorkerService_StopWorker_Call) RunAndReturn(run func(context.Context) error) *MockIWorkerService_StopWorker_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIWorkerService creates a new instance of MockIWorkerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIWorkerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIWorkerService {
	mock := &MockIWorkerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
