// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	json "encoding/json"

	models "github.com/gedyzed/JobFlow/JobService/models"
	mock "github.com/stretchr/testify/mock"
)

// MockIJobRepo is an autogenerated mock type for the IJobRepo type
type MockIJobRepo struct {
	mock.Mock
}

type MockIJobRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIJobRepo) EXPECT() *MockIJobRepo_Expecter {
	return &MockIJobRepo_Expecter{mock: &_m.Mock}
}

// CancelJob provides a mock function with given fields: id
func (_m *MockIJobRepo) CancelJob(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for CancelJob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIJobRepo_CancelJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelJob'
type MockIJobRepo_CancelJob_Call struct {
	*mock.Call
}

// CancelJob is a helper method to define mock.On call
//   - id string
func (_e *MockIJobRepo_Expecter) CancelJob(id interface{}) *MockIJobRepo_CancelJob_Call {
	return &MockIJobRepo_CancelJob_Call{Call: _e.mock.On("CancelJob", id)}
}

func (_c *MockIJobRepo_CancelJob_Call) Run(run func(id string)) *MockIJobRepo_CancelJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIJobRepo_CancelJob_Call) Return(_a0 error) *MockIJobRepo_CancelJob_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIJobRepo_CancelJob_Call) RunAndReturn(run func(string) error) *MockIJobRepo_CancelJob_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIdempotencyKey provides a mock function with given fields: idempotencyKey
func (_m *MockIJobRepo) CreateIdempotencyKey(idempotencyKey *models.IdempotencyKey) error {
	ret := _m.Called(idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateIdempotencyKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.IdempotencyKey) error); ok {
		r0 = rf(idempotencyKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIJobRepo_CreateIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIdempotencyKey'
type MockIJobRepo_CreateIdempotencyKey_Call struct {
	*mock.Call
}

// CreateIdempotencyKey is a helper method to define mock.On call
//   - idempotencyKey *models.IdempotencyKey
func (_e *MockIJobRepo_Expecter) CreateIdempotencyKey(idempotencyKey interface{}) *MockIJobRepo_CreateIdempotencyKey_Call {
	return &MockIJobRepo_CreateIdempotencyKey_Call{Call: _e.mock.On("CreateIdempotencyKey", idempotencyKey)}
}

func (_c *MockIJobRepo_CreateIdempotencyKey_Call) Run(run func(idempotencyKey *models.IdempotencyKey)) *MockIJobRepo_CreateIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.IdempotencyKey))
	})
	return _c
}

func (_c *MockIJobRepo_CreateIdempotencyKey_Call) Return(_a0 error) *MockIJobRepo_CreateIdempotencyKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIJobRepo_CreateIdempotencyKey_Call) RunAndReturn(run func(*models.IdempotencyKey) error) *MockIJobRepo_CreateIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}

// CreateJob provides a mock function with given fields: job
func (_m *MockIJobRepo) CreateJob(job *models.Job) (*models.Job, error) {
	ret := _m.Called(job)

	if len(ret) == 0 {
		panic("no return value specified for CreateJob")
	}

	var r0 *models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Job) (*models.Job, error)); ok {
		return rf(job)
	}
	if rf, ok := ret.Get(0).(func(*models.Job) *models.Job); ok {
		r0 = rf(job)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Job) error); ok {
		r1 = rf(job)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIJobRepo_CreateJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJob'
type MockIJobRepo_CreateJob_Call struct {
	*mock.Call
}

// CreateJob is a helper method to define mock.On call
//   - job *models.Job
func (_e *MockIJobRepo_Expecter) CreateJob(job interface{}) *MockIJobRepo_CreateJob_Call {
	return &MockIJobRepo_CreateJob_Call{Call: _e.mock.On("CreateJob", job)}
}

func (_c *MockIJobRepo_CreateJob_Call) Run(run func(job *models.Job)) *MockIJobRepo_CreateJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Job))
	})
	return _c
}

func (_c *MockIJobRepo_CreateJob_Call) Return(_a0 *models.Job, _a1 error) *MockIJobRepo_CreateJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIJobRepo_CreateJob_Call) RunAndReturn(run func(*models.Job) (*models.Job, error)) *MockIJobRepo_CreateJob_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteJob provides a mock function with given fields: id
func (_m *MockIJobRepo) DeleteJob(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIJobRepo_DeleteJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJob'
type MockIJobRepo_DeleteJob_Call struct {
	*mock.Call
}

// DeleteJob is a helper method to define mock.On call
//   - id string
func (_e *MockIJobRepo_Expecter) DeleteJob(id interface{}) *MockIJobRepo_DeleteJob_Call {
	return &MockIJobRepo_DeleteJob_Call{Call: _e.mock.On("DeleteJob", id)}
}

func (_c *MockIJobRepo_DeleteJob_Call) Run(run func(id string)) *MockIJobRepo_DeleteJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIJobRepo_DeleteJob_Call) Return(_a0 error) *MockIJobRepo_DeleteJob_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIJobRepo_DeleteJob_Call) RunAndReturn(run func(string) error) *MockIJobRepo_DeleteJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetIdempotencyKeyByKey provides a mock function with given fields: idempotencyKey
func (_m *MockIJobRepo) GetIdempotencyKeyByKey(idempotencyKey string) (*models.IdempotencyKey, error) {
	ret := _m.Called(idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for GetIdempotencyKeyByKey")
	}

	var r0 *models.IdempotencyKey
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.IdempotencyKey, error)); ok {
		return rf(idempotencyKey)
	}
	if rf, ok := ret.Get(0).(func(string) *models.IdempotencyKey); ok {
		r0 = rf(idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.IdempotencyKey)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIJobRepo_GetIdempotencyKeyByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIdempotencyKeyByKey'
type MockIJobRepo_GetIdempotencyKeyByKey_Call struct {
	*mock.Call
}

// GetIdempotencyKeyByKey is a helper method to define mock.On call
//   - idempotencyKey string
func (_e *MockIJobRepo_Expecter) GetIdempotencyKeyByKey(idempotencyKey interface{}) *MockIJobRepo_GetIdempotencyKeyByKey_Call {
	return &MockIJobRepo_GetIdempotencyKeyByKey_Call{Call: _e.mock.On("GetIdempotencyKeyByKey", idempotencyKey)}
}

func (_c *MockIJobRepo_GetIdempotencyKeyByKey_Call) Run(run func(idempotencyKey string)) *MockIJobRepo_GetIdempotencyKeyByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIJobRepo_GetIdempotencyKeyByKey_Call) Return(_a0 *models.IdempotencyKey, _a1 error) *MockIJobRepo_GetIdempotencyKeyByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIJobRepo_GetIdempotencyKeyByKey_Call) RunAndReturn(run func(string) (*models.IdempotencyKey, error)) *MockIJobRepo_GetIdempotencyKeyByKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobByID provides a mock function with given fields: id
func (_m *MockIJobRepo) GetJobByID(id string) (*models.Job, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetJobByID")
	}

	var r0 *models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Job, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Job); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIJobRepo_GetJobByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobByID'
type MockIJobRepo_GetJobByID_Call struct {
	*mock.Call
}

// GetJobByID is a helper method to define mock.On call
//   - id string
func (_e *MockIJobRepo_Expecter) GetJobByID(id interface{}) *MockIJobRepo_GetJobByID_Call {
	return &MockIJobRepo_GetJobByID_Call{Call: _e.mock.On("GetJobByID", id)}
}

func (_c *MockIJobRepo_GetJobByID_Call) Run(run func(id string)) *MockIJobRepo_GetJobByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIJobRepo_GetJobByID_Call) Return(_a0 *models.Job, _a1 error) *MockIJobRepo_GetJobByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIJobRepo_GetJobByID_Call) RunAndReturn(run func(string) (*models.Job, error)) *MockIJobRepo_GetJobByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListJobs provides a mock function with no fields
func (_m *MockIJobRepo) ListJobs() ([]*models.Job, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListJobs")
	}

	var r0 []*models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Job, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Job); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIJobRepo_ListJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJobs'
type MockIJobRepo_ListJobs_Call struct {
	*mock.Call
}

// ListJobs is a helper method to define mock.On call
func (_e *MockIJobRepo_Expecter) ListJobs() *MockIJobRepo_ListJobs_Call {
	return &MockIJobRepo_ListJobs_Call{Call: _e.mock.On("ListJobs")}
}

func (_c *MockIJobRepo_ListJobs_Call) Run(run func()) *MockIJobRepo_ListJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIJobRepo_ListJobs_Call) Return(_a0 []*models.Job, _a1 error) *MockIJobRepo_ListJobs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIJobRepo_ListJobs_Call) RunAndReturn(run func() ([]*models.Job, error)) *MockIJobRepo_ListJobs_Call {
	_c.Call.Return(run)
	return _c
}

// RetryJob provides a mock function with given fields: id
func (_m *MockIJobRepo) RetryJob(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for RetryJob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIJobRepo_RetryJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryJob'
type MockIJobRepo_RetryJob_Call struct {
	*mock.Call
}

// RetryJob is a helper method to define mock.On call
//   - id string
func (_e *MockIJobRepo_Expecter) RetryJob(id interface{}) *MockIJobRepo_RetryJob_Call {
	return &MockIJobRepo_RetryJob_Call{Call: _e.mock.On("RetryJob", id)}
}

func (_c *MockIJobRepo_RetryJob_Call) Run(run func(id string)) *MockIJobRepo_RetryJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIJobRepo_RetryJob_Call) Return(_a0 error) *MockIJobRepo_RetryJob_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIJobRepo_RetryJob_Call) RunAndReturn(run func(string) error) *MockIJobRepo_RetryJob_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIdempotencyKeyResponse provides a mock function with given fields: idempotencyKey, response
func (_m *MockIJobRepo) UpdateIdempotencyKeyResponse(idempotencyKey string, response json.RawMessage) error {
	ret := _m.Called(idempotencyKey, response)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIdempotencyKeyResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, json.RawMessage) error); ok {
		r0 = rf(idempotencyKey, response)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIJobRepo_UpdateIdempotencyKeyResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIdempotencyKeyResponse'
type MockIJobRepo_UpdateIdempotencyKeyResponse_Call struct {
	*mock.Call
}

// UpdateIdempotencyKeyResponse is a helper method to define mock.On call
//   - idempotencyKey string
//   - response json.RawMessage
func (_e *MockIJobRepo_Expecter) UpdateIdempotencyKeyResponse(idempotencyKey interface{}, response interface{}) *MockIJobRepo_UpdateIdempotencyKeyResponse_Call {
	return &MockIJobRepo_UpdateIdempotencyKeyResponse_Call{Call: _e.mock.On("UpdateIdempotencyKeyResponse", idempotencyKey, response)}
}

func (_c *MockIJobRepo_UpdateIdempotencyKeyResponse_Call) Run(run func(idempotencyKey string, response json.RawMessage)) *MockIJobRepo_UpdateIdempotencyKeyResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(json.RawMessage))
	})
	return _c
}

func (_c *MockIJobRepo_UpdateIdempotencyKeyResponse_Call) Return(_a0 error) *MockIJobRepo_UpdateIdempotencyKeyResponse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIJobRepo_UpdateIdempotencyKeyResponse_Call) RunAndReturn(run func(string, json.RawMessage) error) *MockIJobRepo_UpdateIdempotencyKeyResponse_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJob provides a mock function with given fields: job
func (_m *MockIJobRepo) UpdateJob(job *models.Job) error {
	ret := _m.Called(job)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Job) error); ok {
		r0 = rf(job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIJobRepo_UpdateJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJob'
type MockIJobRepo_UpdateJob_Call struct {
	*mock.Call
}

// UpdateJob is a helper method to define mock.On call
//   - job *models.Job
func (_e *MockIJobRepo_Expecter) UpdateJob(job interface{}) *MockIJobRepo_UpdateJob_Call {
	return &MockIJobRepo_UpdateJob_Call{Call: _e.mock.On("UpdateJob", job)}
}

func (_c *MockIJobRepo_UpdateJob_Call) Run(run func(job *models.Job)) *MockIJobRepo_UpdateJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Job))
	})
	return _c
}

func (_c *MockIJobRepo_UpdateJob_Call) Return(_a0 error) *MockIJobRepo_UpdateJob_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIJobRepo_UpdateJob_Call) RunAndReturn(run func(*models.Job) error) *MockIJobRepo_UpdateJob_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIJobRepo creates a new instance of MockIJobRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIJobRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIJobRepo {
	mock := &MockIJobRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
