// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIWorkerRepository is an autogenerated mock type for the IWorkerRepository type
type MockIWorkerRepository struct {
	mock.Mock
}

type MockIWorkerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIWorkerRepository) EXPECT() *MockIWorkerRepository_Expecter {
	return &MockIWorkerRepository_Expecter{mock: &_m.Mock}
}

// DeleteJobResult provides a mock function with given fields: ctx, jobID
func (_m *MockIWorkerRepository) DeleteJobResult(ctx context.Context, jobID string) error {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJobResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIWorkerRepository_DeleteJobResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJobResult'
type MockIWorkerRepository_DeleteJobResult_Call struct {
	*mock.Call
}

// DeleteJobResult is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockIWorkerRepository_Expecter) DeleteJobResult(ctx interface{}, jobID interface{}) *MockIWorkerRepository_DeleteJobResult_Call {
	return &MockIWorkerRepository_DeleteJobResult_Call{Call: _e.mock.On("DeleteJobResult", ctx, jobID)}
}

func (_c *MockIWorkerRepository_DeleteJobResult_Call) Run(run func(ctx context.Context, jobID string)) *MockIWorkerRepository_DeleteJobResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIWorkerRepository_DeleteJobResult_Call) Return(_a0 error) *MockIWorkerRepository_DeleteJobResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIWorkerRepository_DeleteJobResult_Call) RunAndReturn(run func(context.Context, string) error) *MockIWorkerRepository_DeleteJobResult_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobResult provides a mock function with given fields: ctx, jobID
func (_m *MockIWorkerRepository) GetJobResult(ctx context.Context, jobID string) (string, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobResult")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIWorkerRepository_GetJobResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobResult'
type MockIWorkerRepository_GetJobResult_Call struct {
	*mock.Call
}

// GetJobResult is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockIWorkerRepository_Expecter) GetJobResult(ctx interface{}, jobID interface{}) *MockIWorkerRepository_GetJobResult_Call {
	return &MockIWorkerRepository_GetJobResult_Call{Call: _e.mock.On("GetJobResult", ctx, jobID)}
}

func (_c *MockIWorkerRepository_GetJobResult_Call) Run(run func(ctx context.Context, jobID string)) *MockIWorkerRepository_GetJobResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIWorkerRepository_GetJobResult_Call) Return(_a0 string, _a1 error) *MockIWorkerRepository_GetJobResult_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIWorkerRepository_GetJobResult_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockIWorkerRepository_GetJobResult_Call {
	_c.Call.Return(run)
	return _c
}

// SaveJobResult provides a mock function with given fields: ctx, jobID, result
func (_m *MockIWorkerRepository) SaveJobResult(ctx context.Context, jobID string, result string) error {
	ret := _m.Called(ctx, jobID, result)

	if len(ret) == 0 {
		panic("no return value specified for SaveJobResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, jobID, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIWorkerRepository_SaveJobResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveJobResult'
type MockIWorkerRepository_SaveJobResult_Call struct {
	*mock.Call
}

// SaveJobResult is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
//   - result string
func (_e *MockIWorkerRepository_Expecter) SaveJobResult(ctx interface{}, jobID interface{}, result interface{}) *MockIWorkerRepository_SaveJobResult_Call {
	return &MockIWorkerRepository_SaveJobResult_Call{Call: _e.mock.On("SaveJobResult", ctx, jobID, result)}
}

func (_c *MockIWorkerRepository_SaveJobResult_Call) Run(run func(ctx context.Context, jobID string, result string)) *MockIWorkerRepository_SaveJobResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIWorkerRepository_SaveJobResult_Call) Return(_a0 error) *MockIWorkerRepository_SaveJobResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIWorkerRepository_SaveJobResult_Call) RunAndReturn(run func(context.Context, string, string) error) *MockIWorkerRepository_SaveJobResult_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJobStatus provides a mock function with given fields: ctx, jobID, status
func (_m *MockIWorkerRepository) UpdateJobStatus(ctx context.Context, jobID string, status string) error {
	ret := _m.Called(ctx, jobID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, jobID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIWorkerRepository_UpdateJobStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJobStatus'
type MockIWorkerRepository_UpdateJobStatus_Call struct {
	*mock.Call
}

// UpdateJobStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
//   - status string
func (_e *MockIWorkerRepository_Expecter) UpdateJobStatus(ctx interface{}, jobID interface{}, status interface{}) *MockIWorkerRepository_UpdateJobStatus_Call {
	return &MockIWorkerRepository_UpdateJobStatus_Call{Call: _e.mock.On("UpdateJobStatus", ctx, jobID, status)}
}

func (_c *MockIWorkerRepository_UpdateJobStatus_Call) Run(run func(ctx context.Context, jobID string, status string)) *MockIWorkerRepository_UpdateJobStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIWorkerRepository_UpdateJobStatus_Call) Return(_a0 error) *MockIWorkerRepository_UpdateJobStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIWorkerRepository_UpdateJobStatus_Call) RunAndReturn(run func(context.Context, string, string) error) *MockIWorkerRepository_UpdateJobStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIWorkerRepository creates a new instance of MockIWorkerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIWorkerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIWorkerRepository {
	mock := &MockIWorkerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
