// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/gedyzed/JobFlow/JobService/models"
	mock "github.com/stretchr/testify/mock"
)

// MockIRMQClient is an autogenerated mock type for the IRMQClient type
type MockIRMQClient struct {
	mock.Mock
}

type MockIRMQClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRMQClient) EXPECT() *MockIRMQClient_Expecter {
	return &MockIRMQClient_Expecter{mock: &_m.Mock}
}

// BindQueue provides a mock function with given fields: ctx, queueName, exchangeName, routingKey
func (_m *MockIRMQClient) BindQueue(ctx context.Context, queueName string, exchangeName string, routingKey string) error {
	ret := _m.Called(ctx, queueName, exchangeName, routingKey)

	if len(ret) == 0 {
		panic("no return value specified for BindQueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, queueName, exchangeName, routingKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRMQClient_BindQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindQueue'
type MockIRMQClient_BindQueue_Call struct {
	*mock.Call
}

// BindQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - queueName string
//   - exchangeName string
//   - routingKey string
func (_e *MockIRMQClient_Expecter) BindQueue(ctx interface{}, queueName interface{}, exchangeName interface{}, routingKey interface{}) *MockIRMQClient_BindQueue_Call {
	return &MockIRMQClient_BindQueue_Call{Call: _e.mock.On("BindQueue", ctx, queueName, exchangeName, routingKey)}
}

func (_c *MockIRMQClient_BindQueue_Call) Run(run func(ctx context.Context, queueName string, exchangeName string, routingKey string)) *MockIRMQClient_BindQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockIRMQClient_BindQueue_Call) Return(_a0 error) *MockIRMQClient_BindQueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRMQClient_BindQueue_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockIRMQClient_BindQueue_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields: ctx
func (_m *MockIRMQClient) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRMQClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIRMQClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIRMQClient_Expecter) Close(ctx interface{}) *MockIRMQClient_Close_Call {
	return &MockIRMQClient_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockIRMQClient_Close_Call) Run(run func(ctx context.Context)) *MockIRMQClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIRMQClient_Close_Call) Return(_a0 error) *MockIRMQClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRMQClient_Close_Call) RunAndReturn(run func(context.Context) error) *MockIRMQClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function with given fields: ctx
func (_m *MockIRMQClient) Connect(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRMQClient_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockIRMQClient_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIRMQClient_Expecter) Connect(ctx interface{}) *MockIRMQClient_Connect_Call {
	return &MockIRMQClient_Connect_Call{Call: _e.mock.On("Connect", ctx)}
}

func (_c *MockIRMQClient_Connect_Call) Run(run func(ctx context.Context)) *MockIRMQClient_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIRMQClient_Connect_Call) Return(_a0 error) *MockIRMQClient_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRMQClient_Connect_Call) RunAndReturn(run func(context.Context) error) *MockIRMQClient_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// DeclareExchange provides a mock function with given fields: ctx, exchangeName, kind
func (_m *MockIRMQClient) DeclareExchange(ctx context.Context, exchangeName string, kind string) error {
	ret := _m.Called(ctx, exchangeName, kind)

	if len(ret) == 0 {
		panic("no return value specified for DeclareExchange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, exchangeName, kind)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRMQClient_DeclareExchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeclareExchange'
type MockIRMQClient_DeclareExchange_Call struct {
	*mock.Call
}

// DeclareExchange is a helper method to define mock.On call
//   - ctx context.Context
//   - exchangeName string
//   - kind string
func (_e *MockIRMQClient_Expecter) DeclareExchange(ctx interface{}, exchangeName interface{}, kind interface{}) *MockIRMQClient_DeclareExchange_Call {
	return &MockIRMQClient_DeclareExchange_Call{Call: _e.mock.On("DeclareExchange", ctx, exchangeName, kind)}
}

func (_c *MockIRMQClient_DeclareExchange_Call) Run(run func(ctx context.Context, exchangeName string, kind string)) *MockIRMQClient_DeclareExchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIRMQClient_DeclareExchange_Call) Return(_a0 error) *MockIRMQClient_DeclareExchange_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRMQClient_DeclareExchange_Call) RunAndReturn(run func(context.Context, string, string) error) *MockIRMQClient_DeclareExchange_Call {
	_c.Call.Return(run)
	return _c
}

// DeclareQueue provides a mock function with given fields: ctx, queueName
func (_m *MockIRMQClient) DeclareQueue(ctx context.Context, queueName string) error {
	ret := _m.Called(ctx, queueName)

	if len(ret) == 0 {
		panic("no return value specified for DeclareQueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, queueName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRMQClient_DeclareQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeclareQueue'
type MockIRMQClient_DeclareQueue_Call struct {
	*mock.Call
}

// DeclareQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - queueName string
func (_e *MockIRMQClient_Expecter) DeclareQueue(ctx interface{}, queueName interface{}) *MockIRMQClient_DeclareQueue_Call {
	return &MockIRMQClient_DeclareQueue_Call{Call: _e.mock.On("DeclareQueue", ctx, queueName)}
}

func (_c *MockIRMQClient_DeclareQueue_Call) Run(run func(ctx context.Context, queueName string)) *MockIRMQClient_DeclareQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIRMQClient_DeclareQueue_Call) Return(_a0 error) *MockIRMQClient_DeclareQueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRMQClient_DeclareQueue_Call) RunAndReturn(run func(context.Context, string) error) *MockIRMQClient_DeclareQueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewConsumer provides a mock function with given fields: ctx, queueName
func (_m *MockIRMQClient) NewConsumer(ctx context.Context, queueName string) (models.Consumer, error) {
	ret := _m.Called(ctx, queueName)

	if len(ret) == 0 {
		panic("no return value specified for NewConsumer")
	}

	var r0 models.Consumer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Consumer, error)); ok {
		return rf(ctx, queueName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Consumer); ok {
		r0 = rf(ctx, queueName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.Consumer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, queueName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRMQClient_NewConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewConsumer'
type MockIRMQClient_NewConsumer_Call struct {
	*mock.Call
}

// NewConsumer is a helper method to define mock.On call
//   - ctx context.Context
//   - queueName string
func (_e *MockIRMQClient_Expecter) NewConsumer(ctx interface{}, queueName interface{}) *MockIRMQClient_NewConsumer_Call {
	return &MockIRMQClient_NewConsumer_Call{Call: _e.mock.On("NewConsumer", ctx, queueName)}
}

func (_c *MockIRMQClient_NewConsumer_Call) Run(run func(ctx context.Context, queueName string)) *MockIRMQClient_NewConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIRMQClient_NewConsumer_Call) Return(_a0 models.Consumer, _a1 error) *MockIRMQClient_NewConsumer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRMQClient_NewConsumer_Call) RunAndReturn(run func(context.Context, string) (models.Consumer, error)) *MockIRMQClient_NewConsumer_Call {
	_c.Call.Return(run)
	return _c
}

// NewPublisher provides a mock function with given fields: ctx, target
func (_m *MockIRMQClient) NewPublisher(ctx context.Context, target models.PublisherTarget) (models.Publisher, error) {
	ret := _m.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for NewPublisher")
	}

	var r0 models.Publisher
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.PublisherTarget) (models.Publisher, error)); ok {
		return rf(ctx, target)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.PublisherTarget) models.Publisher); ok {
		r0 = rf(ctx, target)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.Publisher)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.PublisherTarget) error); ok {
		r1 = rf(ctx, target)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRMQClient_NewPublisher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewPublisher'
type MockIRMQClient_NewPublisher_Call struct {
	*mock.Call
}

// NewPublisher is a helper method to define mock.On call
//   - ctx context.Context
//   - target models.PublisherTarget
func (_e *MockIRMQClient_Expecter) NewPublisher(ctx interface{}, target interface{}) *MockIRMQClient_NewPublisher_Call {
	return &MockIRMQClient_NewPublisher_Call{Call: _e.mock.On("NewPublisher", ctx, target)}
}

func (_c *MockIRMQClient_NewPublisher_Call) Run(run func(ctx context.Context, target models.PublisherTarget)) *MockIRMQClient_NewPublisher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.PublisherTarget))
	})
	return _c
}

func (_c *MockIRMQClient_NewPublisher_Call) Return(_a0 models.Publisher, _a1 error) *MockIRMQClient_NewPublisher_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRMQClient_NewPublisher_Call) RunAndReturn(run func(context.Context, models.PublisherTarget) (models.Publisher, error)) *MockIRMQClient_NewPublisher_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRMQClient creates a new instance of MockIRMQClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRMQClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRMQClient {
	mock := &MockIRMQClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
