// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockIObjectStorage is an autogenerated mock type for the IObjectStorage type
type MockIObjectStorage struct {
	mock.Mock
}

type MockIObjectStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIObjectStorage) EXPECT() *MockIObjectStorage_Expecter {
	return &MockIObjectStorage_Expecter{mock: &_m.Mock}
}

// DeleteObject provides a mock function with given fields: ctx, objectKey
func (_m *MockIObjectStorage) DeleteObject(ctx context.Context, objectKey string) error {
	ret := _m.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, objectKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIObjectStorage_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockIObjectStorage_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *MockIObjectStorage_Expecter) DeleteObject(ctx interface{}, objectKey interface{}) *MockIObjectStorage_DeleteObject_Call {
	return &MockIObjectStorage_DeleteObject_Call{Call: _e.mock.On("DeleteObject", ctx, objectKey)}
}

func (_c *MockIObjectStorage_DeleteObject_Call) Run(run func(ctx context.Context, objectKey string)) *MockIObjectStorage_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIObjectStorage_DeleteObject_Call) Return(_a0 error) *MockIObjectStorage_DeleteObject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIObjectStorage_DeleteObject_Call) RunAndReturn(run func(context.Context, string) error) *MockIObjectStorage_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function with given fields: ctx, objectKey
func (_m *MockIObjectStorage) GetObject(ctx context.Context, objectKey string) (io.Reader, error) {
	ret := _m.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 io.Reader
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.Reader, error)); ok {
		return rf(ctx, objectKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.Reader); ok {
		r0 = rf(ctx, objectKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, objectKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIObjectStorage_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MockIObjectStorage_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *MockIObjectStorage_Expecter) GetObject(ctx interface{}, objectKey interface{}) *MockIObjectStorage_GetObject_Call {
	return &MockIObjectStorage_GetObject_Call{Call: _e.mock.On("GetObject", ctx, objectKey)}
}

func (_c *MockIObjectStorage_GetObject_Call) Run(run func(ctx context.Context, objectKey string)) *MockIObjectStorage_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIObjectStorage_GetObject_Call) Return(_a0 io.Reader, _a1 error) *MockIObjectStorage_GetObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIObjectStorage_GetObject_Call) RunAndReturn(run func(context.Context, string) (io.Reader, error)) *MockIObjectStorage_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function with given fields: ctx, objectKey, data, contentType
func (_m *MockIObjectStorage) PutObject(ctx context.Context, objectKey string, data io.Reader, contentType *string) error {
	ret := _m.Called(ctx, objectKey, data, contentType)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, *string) error); ok {
		r0 = rf(ctx, objectKey, data, contentType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIObjectStorage_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type MockIObjectStorage_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
//   - data io.Reader
//   - contentType *string
func (_e *MockIObjectStorage_Expecter) PutObject(ctx interface{}, objectKey interface{}, data interface{}, contentType interface{}) *MockIObjectStorage_PutObject_Call {
	return &MockIObjectStorage_PutObject_Call{Call: _e.mock.On("PutObject", ctx, objectKey, data, contentType)}
}

func (_c *MockIObjectStorage_PutObject_Call) Run(run func(ctx context.Context, objectKey string, data io.Reader, contentType *string)) *MockIObjectStorage_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(*string))
	})
	return _c
}

func (_c *MockIObjectStorage_PutObject_Call) Return(_a0 error) *MockIObjectStorage_PutObject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIObjectStorage_PutObject_Call) RunAndReturn(run func(context.Context, string, io.Reader, *string) error) *MockIObjectStorage_PutObject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIObjectStorage creates a new instance of MockIObjectStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIObjectStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIObjectStorage {
	mock := &MockIObjectStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
